name: Trigger On PHP Request

on:
  repository_dispatch:
    types:
      - php_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq (JSON processor)
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Update JSON file
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Fetch the secret value
        run: |
          # Store the JSON content in a variable
          JSON_CONTENT=$(cat database.js)

          # Update the title of the first block under "page1" to "hello"
          JSON_CONTENT=$(echo "$JSON_CONTENT" | jq '.pages.page1.blocks[0].title = "hello"')

          # Write the updated JSON content back to the file
          echo "$JSON_CONTENT" > database.js

          # Commit the changes and push
          git config --global user.email "timmeeuwsen@hotmail.nl"
          git config --global user.name "timmit147"
          git add database.js
          git commit -m "Update title of the first block in page1"
          git push -u origin HEAD

