name: My Custom Workflow

on:
  workflow_dispatch:
    inputs:
      myInputParameter:
        required: true
        description: 'A parameter to pass data from the client-side'

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Input Parameter
        run: echo "Input Parameter: ${{ github.event.inputs.myInputParameter }}"
